"""Row data for every neighbour table this artifact produces.

Each row follows the plan's schema. `raw_file` names the file under results/raw/
that holds the grep/fetch output the quote was copied from; build_tables.py
checks that the quote occurs in that file (after whitespace / line-break
normalisation) and that it is <= 40 words.

verified_flag is one of: VERIFIED-QUOTE, PARAPHRASE-ONLY, NOT VERIFIED, CARRIED.
Every row's access date is 2026-09-24 (the executor's real run date).
"""

ACCESS = "2026-09-24"
DEP = "art_sZ5w0yoY9o6L (iter_4/gen_art/gen_art_research_1)"

# ---------------------------------------------------------------------------
# T2 - measurement-claim neighbours (M rows)
# ---------------------------------------------------------------------------
MEASUREMENT = [
    dict(
        id="M1", subclaim="B1",
        claim_positioned="substring/non-refusal metrics over-report how much refusal was removed",
        citation="Souly et al., 2024, 'A StrongREJECT for Empty Jailbreaks', arXiv 2402.10260",
        quote="Most of the baseline automated evaluators overestimate how effective jailbreak methods are on average, especially string matching for non-refusal.",
        locator="Sec. 3.2 (discussion of Table 1, 'StrongREJECT is less biased than automated evaluators in prior work')",
        url="https://arxiv.org/pdf/2402.10260",
        verified_flag="VERIFIED-QUOTE",
        establishes="At evaluation time, string matching for non-refusal is the most biased of the automated evaluators tested against human labels.",
        where_this_run_stops="This run does not claim that substring rules are bad (published here); it claims only the measured inversion: near-exact on unedited checkpoints, collapsing on the edited ones, and used as the optimiser's objective.",
        narrows="YES - owns the general point",
        raw_file="g_2402.10260_q.txt",
    ),
    dict(
        id="M2", subclaim="B1",
        claim_positioned="substring/non-refusal metrics over-report removal (the neighbour the plan expected to be closest)",
        citation="Mu, 2026, 'An Empirical Measurement of Jailbreaking Evaluators', arXiv 2609.10594 (v1, 7 Sep 2026)",
        quote="This approach is inexpensive and fully reproducible, but it provides only a weak proxy for actual compliance",
        locator="Sec. 2 Background (on string matching); results in Sec. 5 / Fig. 1",
        url="https://arxiv.org/pdf/2609.10594",
        verified_flag="VERIFIED-QUOTE",
        establishes="Compares six LLM-based evaluators (HarmBench, JailbreakBench, JailbreakRadar, StrongReject, JADES, JailMeter) against human labels; string matching appears only as background, not as a measured arm.",
        where_this_run_stops="CORRECTION to the plan: the sentence 'automated evaluators, string matching for non-refusal above all, overestimate' is StrongREJECT's (M1), not this paper's. 2609.10594 narrows the evaluator-choice point, not the edited-condition inversion.",
        narrows="PARTLY - evaluator choice moves ASR; does not measure substring rules",
        raw_file="g_2609.10594_string.txt",
    ),
    dict(
        id="M3", subclaim="B1",
        claim_positioned="substring refusal counting over-reports refusal on ABLITERATED outputs specifically",
        citation="Agnihotri, Jakubassa, Dey, Goyal, Schiele, Babu, Keuper, 2025, 'A Granular Study of Safety Pretraining under Model Abliteration', arXiv 2510.02768 (NeurIPS 2025 Workshop Lock-LLM)",
        quote="Bias analysis indicates that regex tends to overestimate refusals by flagging templated disclaimers in otherwise harmless answers",
        locator="Sec. 4.2 'Study 2: Human-grounded validation of judges'",
        url="https://arxiv.org/pdf/2510.02768",
        verified_flag="VERIFIED-QUOTE",
        establishes="On 20 systems (10 base models and their abliterated versions) a regex refusal detector over-counts refusals because disclaimers trigger it; hybrid 'cautionary preface then substantive guidance' outputs are the typical failure.",
        where_this_run_stops="This is the MECHANISM this run measured, already published for abliterated models. What it does not report: agreement WITHIN the edited condition versus the unedited one (validated on a 10-prompt human subset, Pearson correlation, pooled), a non-English language, or the counter used as an optimiser objective.",
        narrows="YES - shrinks the B1 delta to magnitude, within-condition measurement, language, and use-as-objective",
        raw_file="g_2510.02768_regex.txt",
    ),
    dict(
        id="M4", subclaim="B1",
        claim_positioned="the Heretic-ecosystem refusal counter is a coarse proxy (practitioner-facing evaluation)",
        citation="Young, 2025, 'Comparative Analysis of LLM Abliteration Methods: A Cross-Architecture Evaluation', arXiv 2512.13655 (v2, 8 Jan 2026)",
        quote="This approach can produce false positives (responses that mention safety language while still providing actionable content) and false negatives (refusals phrased without the selected markers).",
        locator="Sec. 3 metrics, 'Refusal/ASR Validity' paragraph",
        url="https://arxiv.org/pdf/2512.13655",
        verified_flag="VERIFIED-QUOTE",
        establishes="Evaluates Heretic (and three other tools) with a marker-substring refusal heuristic and states the false-positive direction as a caveat, without measuring it.",
        where_this_run_stops="States the caveat; this run measures it (false-positive share .761 on the shipped Gemma edit, kappa -.04). Cited as a caveat that already exists, not as a measurement.",
        narrows="WEAKLY - caveat stated, not quantified",
        raw_file="g_2512.13655_fp.txt",
    ),
    dict(
        id="M5", subclaim="B1/B2",
        claim_positioned="refusal-keyword matching used as an OBJECTIVE (counter-example: optimised, not audited)",
        citation="Zhou et al., 2024, 'Don't Say No: Jailbreaking LLM by Suppressing Refusal' (DSN), arXiv 2404.16369",
        quote="The primarily employed evaluation method is Refusal Matching, which checks whether the initial segments of the response contain pre-defined refusal sub-strings.",
        locator="Sec. 2 Related Work, 'Jailbreak evaluation'",
        url="https://arxiv.org/pdf/2404.16369",
        verified_flag="VERIFIED-QUOTE",
        establishes="Refusal-substring matching is the dominant evaluator, and DSN builds its attack loss on suppressing refusal keywords (the literature optimises against this proxy).",
        where_this_run_stops="Prompt-attack setting; no weight edits and no audit of the proxy on the optimiser's own candidates.",
        narrows="NO - context",
        raw_file="g_2404.16369_q.txt",
    ),
    dict(
        id="M6", subclaim="B1",
        claim_positioned="metric and judge quality for harmfulness scoring",
        citation="Yang et al., 2025, 'HarmMetric Eval: Benchmarking Metrics and Judges for LLM Harmfulness Assessment', arXiv 2509.24384 (v3, 18 Mar 2026)",
        quote="conventional reference-based metrics such as ROUGE and METEOR can outperform LLM-based judges in fine-grained harmfulness evaluation",
        locator="abstract",
        url="https://arxiv.org/abs/2509.24384",
        verified_flag="VERIFIED-QUOTE",
        establishes="Metric/judge rankings are not what practitioners assume; LLM judges mis-rate irrelevant or useless outputs.",
        where_this_run_stops="Harmfulness ranking on a curated set, English; no edited models, no refusal counter.",
        narrows="NO - context",
        raw_file="abs_2509.24384.txt",
    ),
    dict(
        id="M7", subclaim="B1/B4",
        claim_positioned="judge calibration and robustness for ASR scoring",
        citation="anonymous, 2026, 'How Reliable Is Your Jailbreak Judge? Calibration and Adversarial Robustness of Automated ASR Scoring', arXiv 2606.25487",
        quote="Wrappers that leave the harmful text untouched and only add benign framing flip every LLM-judge between 57% and 100% of the time",
        locator="abstract",
        url="https://arxiv.org/abs/2606.25487",
        verified_flag="CARRIED",
        establishes="ASR judges are fragile to benign framing, which is the surface form caveat-laden edited outputs take.",
        where_this_run_stops="Carried from the dependency (N18) without re-verification.",
        narrows="PARTLY",
        raw_file="(dependency) results/raw/2606_25487.txt",
    ),
    dict(
        id="M8", subclaim="B2",
        claim_positioned="selection blindness inside the abliteration search (companion result)",
        citation="Zhu, Amos, Tian, Guo, Evtimov, 2024, 'AdvPrefix: An Objective for Nuanced LLM Jailbreaks', arXiv 2412.10321 (v2, 27 Dec 2025)",
        quote="Misspecified: even with low optimization loss, actual responses are often incomplete or unfaithful",
        locator="Sec. 1 Introduction",
        url="https://arxiv.org/pdf/2412.10321",
        verified_flag="VERIFIED-QUOTE",
        establishes="A misspecified objective inside an optimiser gives low loss without the intended behaviour, and replacing it changes what the search finds (GCG on Llama-3 nuanced ASR 14% -> 80%).",
        where_this_run_stops="AdvPrefix owns objective misspecification for prompt-attack objectives. This run positions only its weight-edit instance: structural threshold blindness shared by both searches, measured on the search's own candidates. AdvPrefix is NOT a neighbour for the placement result.",
        narrows="YES - owns the general point",
        raw_file="g_2412.10321_missp.txt",
    ),
    dict(
        id="M9", subclaim="B4 (and B3)",
        claim_positioned="a scoring rule certified on one output distribution degrades on a shifted one (edited/attacked outputs)",
        citation="Schwinn, Ladenburger, Beyer, Mofakhami, Gidel, Guennemann, 2026, 'A Coin Flip for Safety: LLM Judges Fail to Reliably Measure Adversarial Robustness', arXiv 2603.06594 (v2, 15 Mar 2026)",
        quote="we show that existing validation protocols fail to account for substantial distribution shifts inherent to red-teaming: diverse victim models exhibit distinct generation styles, attacks distort output patterns",
        locator="abstract (also: 'judge performance to degrade to near random chance', 6642 human-verified labels)",
        url="https://arxiv.org/abs/2603.06594",
        verified_flag="VERIFIED-QUOTE",
        establishes="Judges validated on static held-out sets degrade, often to near chance, when victim model and attack shift the output distribution; attacks inflate ASR by exploiting judge insufficiencies.",
        where_this_run_stops="This is the published form of 'certify within the condition you score'. What remains for this run is the weight-edit and cross-lingual instance: within-edited kappa of the keyword counter 0.02 EN / 0.00 SL on held-out categories, and the 0.133 pooled-vs-within inflation.",
        narrows="YES - shrinks the within-edited-agreement move to an instance",
        raw_file="g_2603.06594.txt",
    ),
    dict(
        id="M10", subclaim="B3",
        claim_positioned="guard pipeline and LLM judge reported SEPARATELY on abliterated checkpoints",
        citation="Abu Shairah, Hammoud, Ghanem, Turkiyyah, 2025, 'An Embarrassingly Simple Defense Against LLM Abliteration Attacks', arXiv 2505.19056 (v2, 7 Oct 2025)",
        quote="Overall, the two methods are in strong agreement, with differences of at most 4 percentage points.",
        locator="Appendix A 'LLM as a Judge vs Llama-Guard', Table 4 (92.7 vs 90.4; 90.9 vs 94.6; 96.7 vs 89.3)",
        url="https://arxiv.org/pdf/2505.19056v2",
        verified_flag="VERIFIED-QUOTE",
        establishes="Qwen-2.5-14B judge and Llama-Guard-3-8B refusal rates reported side by side for abliterated extended-refusal models, in English, on CatQA; the two channels agree within 4 points.",
        where_this_run_stops="The practice this run insists on is published. What differs is the finding: on the shipped Gemma edit the two channels DIVERGE, and in a language-dependent way (non-refusals guard-safe +0.232 more often in SL than EN).",
        narrows="YES - on practice; NO - on the language-dependent divergence",
        raw_file="g_2505.19056_appA.txt",
    ),
    dict(
        id="M11", subclaim="B3",
        claim_positioned="three-task moderation (prompt harm, response harm, refusal) as separate channels",
        citation="Han, Rao, Ettinger, Jiang, Lin, Lambert, Choi, Dziri, 2024, 'WildGuard: Open One-Stop Moderation Tools for Safety Risks, Jailbreaks, and Refusals of LLMs', arXiv 2406.18495",
        quote="(1) identifying malicious intent in user prompts, (2) detecting safety risks of model responses, and (3) determining model refusal rate",
        locator="abstract",
        url="https://arxiv.org/pdf/2406.18495",
        verified_flag="VERIFIED-QUOTE",
        establishes="Response harmfulness and refusal are standard, separately scored moderation tasks.",
        where_this_run_stops="Standard framing; no edited checkpoints, no language comparison.",
        narrows="NO - context",
        raw_file="g_2406.18495_q.txt",
    ),
    dict(
        id="M12", subclaim="B3",
        claim_positioned="an explicit PARTIAL class",
        citation="Roettger et al., 2024, 'XSTest: A Test Suite for Identifying Exaggerated Safety Behaviours', arXiv 2308.01263",
        quote="Partial Refusal is any combination of refusal and compliance.",
        locator="Sec. 4.2 response types",
        url="https://arxiv.org/pdf/2308.01263",
        verified_flag="VERIFIED-QUOTE",
        establishes="Three-way human annotation: full compliance, full refusal, partial refusal.",
        where_this_run_stops="XSTest classes are human-annotated; this run's are automatic with native review pending.",
        narrows="YES - on the partial class",
        raw_file="g_2308.01263_q.txt",
    ),
    dict(
        id="M13", subclaim="B3",
        claim_positioned="refusal taxonomy beyond refuse/comply",
        citation="Li, Wang, Li, Jones, 2026, 'You Shouldn't Have Asked: A Pragmatics-Inspired Taxonomy for Evaluating LLM Refusals', arXiv 2608.30856",
        quote="their refusals are overall explicit and strongly morally evaluative",
        locator="abstract",
        url="https://arxiv.org/abs/2608.30856",
        verified_flag="VERIFIED-QUOTE",
        establishes="A pragmatics taxonomy of refusal FORMS over 16 LLMs and 14 harm categories.",
        where_this_run_stops="About how models refuse, not partial compliance in edited models; the grep for 'partial' did not isolate a partial-compliance class.",
        narrows="NO - context",
        raw_file="abs_2608.30856.txt",
    ),
    dict(
        id="M14", subclaim="B3",
        claim_positioned="the RefusEU guard pipeline (which guard pipeline this run actually ran)",
        citation="Krasnodebska, Kusa, Lipani et al., 2026, 'Multilingual Refusal Alignment for Safer Large Language Models' (RefusEU), arXiv 2606.07535, Findings ACL 2026",
        quote="the compliance responses were labeled as unsafe (by at least one of the two guard models) were retained",
        locator="Sec. 3 (dataset construction); guard models Llama-Guard-3-8B and PolyGuard-Qwen, GPT-4o-mini compared in Fig. 2",
        url="https://arxiv.org/pdf/2606.07535",
        verified_flag="VERIFIED-QUOTE",
        establishes="RefusEU's data pipeline uses TWO guards (Llama-Guard-3-8B and PolyGuard-Qwen): refusals kept only if both call them safe, compliances kept if at least one calls them unsafe.",
        where_this_run_stops="The paper should name the pipeline as 'Llama-Guard-3-8B and PolyGuard-Qwen (the RefusEU guard pair)', not 'the official guard'. The exact ASR-scoring rule of RefusEU's Sec. 4 evaluation was not isolated by these greps.",
        narrows="NO - naming repair",
        raw_file="g_2606.07535_pipe.txt",
    ),
    dict(
        id="M15", subclaim="B3",
        claim_positioned="the residual cross-lingual asymmetry is action, not representation",
        citation="Aziz, Hanif, Koto, 2026, 'Low-Resource Safety Failures Are Action Failures, Not Representation Failures', arXiv 2606.01196",
        quote="What fails to transfer is calibration of the safety decision, not the underlying representation.",
        locator="abstract (HTML v1); also 'The relevant representation is present. Yet harmful refusal drops from 87.9% to 43.9%.'",
        url="https://arxiv.org/html/2606.01196",
        verified_flag="VERIFIED-QUOTE",
        establishes="On unedited models across 23 languages, harmfulness remains decodable while refusal fails to fire; a threshold recalibration fixes much of it.",
        where_this_run_stops="Partly anticipates this run's 'actionability' reading. This run's version is on the REMOVAL side (after an English-selected edit) and concerns whether non-refusals are actionable, which is a different quantity from refusal.",
        narrows="YES - conceptually",
        raw_file="g_2606.01196_q.txt",
    ),
    dict(
        id="M16", subclaim="B4",
        claim_positioned="LLM-judge reliability is language-conditional",
        citation="Dogruoz, Liao, Blaschke, Prange, Li, Adelani, 2026, 'Challenges and Recommendations for LLM-as-a-Judge in Multilingual Settings and for Low-Resource Languages', arXiv 2607.02235 (v2), EMNLP Findings 2026",
        quote="judge reliability is language-conditional rather than uniform",
        locator="analysis section, paragraph ending 'Therefore, the problem is not that validation is rare'",
        url="https://arxiv.org/pdf/2607.02235",
        verified_flag="VERIFIED-QUOTE",
        establishes="Survey of 33 multilingual LLM-as-judge papers: over-trust, single-judge reliance, and agreement that drops for lower-resource and non-Latin-script languages (citing Watts 2024, Fu and Liu 2025, Hada 2024).",
        where_this_run_stops="CORRECTION to the plan: the '~80%' figure in this paper is Zheng et al.'s ENGLISH MT-Bench agreement, and no '<60%' figure was found. The paper must present the Slovene judge-gate failures (SL 0.723-0.744 vs EN 0.856-0.871) as an instance of a known problem.",
        narrows="YES",
        raw_file="g_2607.02235_agree.txt",
    ),
    dict(
        id="M17", subclaim="B4",
        claim_positioned="judge-human agreement drops in lower-resource languages (safety/jailbreak setting)",
        citation="Akinode, Li, Hamidouche, Zamir, Becker-Reshef, Adelani, 2026, 'TukaBench: A Culturally Grounded Jailbreak Benchmark for African Languages', arXiv 2606.01322 (v2)",
        quote="showing that judge-human agreement drops in lower-resource languages and less commonly supported scripts",
        locator="abstract",
        url="https://arxiv.org/abs/2606.01322",
        verified_flag="VERIFIED-QUOTE",
        establishes="In a jailbreak benchmark, the LLM judge's human agreement falls for lower-resource languages; adds a 'Deflection' class.",
        where_this_run_stops="Unedited models, African languages; not within an edited condition and not a Slavic language.",
        narrows="YES",
        raw_file="abs_2606.01322.txt",
    ),
]

MEASUREMENT += [{'id': 'M18', 'subclaim': 'B4 (CONTRADICTING)', 'claim_positioned': 'a judge CAN hold across languages when it is validated per language', 'citation': "Zhang, Patel, Truong, Koyejo, 2026, 'Why Do Safety Guardrails Degrade Across Languages?', arXiv 2605.17173 (v2), COLM 2026", 'quote': "agreement is substantial: Cohen's \u03ba = 0.80\u20130.83, with 93.2\u201396.6% binary agreement", 'locator': "Sec. 3 'Safety judgment and validation' (300 stratified responses, 10 languages x 3 models; reported kappa 0.80-0.83, 93.2-96.6% binary agreement)", 'url': 'https://arxiv.org/pdf/2605.17173', 'verified_flag': 'VERIFIED-QUOTE', 'establishes': "CONTRADICTING evidence for a blanket 'judges fail in other languages' reading: a frontier judge validated per language on 300 stratified responses reaches kappa 0.80-0.83 with two human annotators across 10 languages. Also finds 22 of 61 configurations more vulnerable in English than in low-resource languages.", 'where_this_run_stops': "The paper must NOT claim multilingual judges fail in general. The honest statement is that THIS run's local judge, certified in English, lost agreement in Slovene within the edited condition; a stronger judge validated per language may not.", 'narrows': 'CONTRADICTS the strong form of the claim', 'raw_file': 'g_2605.17173_q.txt'}, {'id': 'M19', 'subclaim': 'B4', 'claim_positioned': 'judge validation practice: agreement must be reported where it is used', 'citation': "Alloula, Licini, Batchkala, Goldfarb-Tarrant, 2026, 'Safety is Contextual, LLM-Judges Are Not: Navigating the Rigid Priors of Evaluators', arXiv 2606.07874", 'quote': 'they are broadly unlikely to adjust their evaluations if the context or safety definition contradicts their prior', 'locator': 'abstract', 'url': 'https://arxiv.org/abs/2606.07874', 'verified_flag': 'VERIFIED-QUOTE', 'establishes': 'Safety judges resist a changed safety definition, so a rubric certified under one definition does not transfer to another.', 'where_this_run_stops': 'English, unedited outputs; no within-condition agreement measurement.', 'narrows': 'NO - context', 'raw_file': 'g_2606.07874.txt'}, {'id': 'M20', 'subclaim': 'B1 (community practice)', 'claim_positioned': 'abliteration refusal benchmarks are widely mis-measured in the practitioner ecosystem', 'citation': 'abliterix (wuwangzhang1216), evaluation methodology, docs/evaluation.md, state as of 2026-09-24', 'quote': 'We tested a prominent "3/100" model and measured **60/100 refusals** with our pipeline.', 'locator': "docs/evaluation.md, 'Honest evaluation matters' bullet and 'The problem with current benchmarks'", 'url': 'https://github.com/wuwangzhang1216/abliterix/blob/master/docs/evaluation.md', 'verified_flag': 'VERIFIED-QUOTE', 'establishes': "A community tool documents that short generation lengths hide a 'delayed refusal' pattern, so published abliteration refusal rates are not reproducible; it also uses Optuna TPE multi-objective search.", 'where_this_run_stops': 'Non-peer-reviewed practitioner documentation, English, no judge certification. Cited as evidence that the measurement problem is live in the ecosystem, not as a scientific result.', 'narrows': 'PARTLY - on the practitioner point', 'raw_file': 'g_abliterix_eval.txt'}, {'id': 'M21', 'subclaim': 'B1 (tool state)', 'claim_positioned': 'the JailbreakBench refusal-prefix rule is matched anywhere rather than as a prefix', 'citation': 'JailbreakBench issue #50 (collapseindex), opened 16 Sep 2026', 'quote': 'the verdict is discarded under 15 tokens, and `TEST_PREFIXES` is matched anywhere rather than as a prefix', 'locator': 'issue title', 'url': 'https://github.com/JailbreakBench/jailbreakbench/issues/50', 'verified_flag': 'VERIFIED-QUOTE', 'establishes': "An open defect report on a standard benchmark's classifier: substring matching applied anywhere in the response, the same failure mode this run measured in a refusal counter.", 'where_this_run_stops': 'An unresolved issue report, not a peer-reviewed measurement; cited only as dated evidence that the defect class is recognised in tooling.', 'narrows': 'NO - context', 'raw_file': 'g_jbb_issue50.txt'}]
